[listener]
type="socket"

[service.http]
type="http"
server="Apache"

[[port]]
port="tcp/80"
services=["http"]

[service.ssh-simulator]
type="ssh-simulator"
credentials=["root:root", "root:password"]

[[port]]
port="tcp/8080"
services=["ssh-simulator"]

[service.telnet]
type="telnet"
prompt=">>"

[[port]]
port="tcp/23"
services=["telnet"]

[channel.console]
type="console"

[channel.elasticsearch]
type="elasticsearch"
url="http://elasticsearch:9200/honeytrap"

[[filter]]
channel=["console", "elasticsearch"]

[[logging]]
output = "stdout"
level = "debug"
